version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: tride_mongo
    ports:
      - "27017:27017"
    env_file:
      - .env.mongo
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:


